language: python
python:
- '3.6'
- '3.7'
- '3.8'
install: bash build_tools/travis/install.sh
script: pytest
deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
  skip_cleanup: true
  skip_existing: true
  password:
    secure: L0d1idTnchbwzXYsUi/RIDX6rY/ZdxqBX1EEqXgXDIQFEIOfA9Es0Sd7+U0QlKgmxUl9gjlRErHOth4L8opZjY+g8FSJJSHPcJLN8vsfwZC0bfTLxiKhtq78NNQfhkerWgYTVxtLiTUhdp4NKTZtyAy+4RTo6BTv51EdsoenD2htYGmfh3PdB+7jJLmbrfsZeSZSdTyZMRX/0FAGf8wrF6jMTi5qAKuqtsB+kJvTNKiNukbNcqxp8uudfYu2uOYqJ28WCgIGL1usuvoSUV9kRCAVSweAaP6SiZRvte0ZlL7RyqrmflS6EMtkRPOacLtK3Oh2k38aQalv81JJ9PtJEHm8L0OGSQxW+vfRyV+RhdBkFlWyn3pG6PbXoVVwYHArts4hdXMP+11hyofaOeci98+woAg/fkX+/BmJFWhkbv8xCt2UiMhZ6kjziNhe/mFw0XSgkuoM+IZKOM3FIiXyo9F1icCc5NCcorqMutWsxYFMBMCAbTQXgP+5THGHLNfBALGoCzegP3VW3oQQytds845C/M6U2OVSXrjw6UyF5BPf0fvpthAubebqOaThwP+A522ithEbRK/pv543nr7a8OMV10mQYWG8zESdaO6+1fHZ2MBFEtQCUL4wd0Ucr58G/66w6NcRdeyXucsmy6WtDpAbr6QSv/x+VOUqIIXRaC0=
